import { environment } from 'src/environments/environment';

const prefixUrl = `${environment.apiPrefix}${environment.apiVersion}`;
const serverUrl = `${environment.serverUrl}`;
const cloudFilePath = `${environment.cloudFilePath}`;

export const API_URL = {
    register: `${prefixUrl}/login/register`,
    login: `${prefixUrl}/auth/login`,
    siteList: `${prefixUrl}/master/sites`,
    source: `${prefixUrl}/master/biolabs-source`,
    companyStage: `${prefixUrl}/master/technology-stage`,
    fundingOptions: `${prefixUrl}/master/fundings`,
    modality: `${prefixUrl}/master/modality`,
    industry: `${prefixUrl}/master/category`,
    useList: `${prefixUrl}/user`,
    addUser: `${prefixUrl}/user`,
    verifyUser: prefixUrl + `/auth/verify-link/`,
    setNewPassword: prefixUrl + `/auth/set-password`,
    forgotPassword: prefixUrl + `/auth/forgot-password`,
    residentCompany: prefixUrl + `/resident-company`,
    companyStatus: prefixUrl + `/master/company-status`,
    userType: prefixUrl + `/master/user-types`,
    companyStatusUpdate: prefixUrl + `/resident-company/update-status`,
    forwardApp: prefixUrl + `/resident-company`,
    uploadFile: prefixUrl + `/file/upload`,
    userProfilePic: prefixUrl + `/file/upload?fileType=user&userId=`,
    readProfilePic: `${serverUrl}${prefixUrl}/file/read-image?fileType=user&filename=`,
    readLogoURL: `${serverUrl}${prefixUrl}/file/read-image?fileType=logo&filename=`,
    readSponsorLogoURL: `${serverUrl}${prefixUrl}/file/read-image?fileType=sponsorlogo&filename=`,
    pitchDeck: `${cloudFilePath}/pitchdeck/`,
    sponsorGlobalData: `${prefixUrl}/sponsor/global-data`,
    sponsorSiteData: `${prefixUrl}/sponsor/site-data`,
    searchCompany: `${prefixUrl}/resident-company/search`,
    invoiceOrderProduct: `${prefixUrl}/order-product`,
    retainerProductToDate: `${prefixUrl}/order-product/retainer`,
    committeeStatus: `${prefixUrl}/master/committee-status`,
    notes: `${prefixUrl}/resident-company/notes`,
    member: `${prefixUrl}/resident-company/member-list`,
    addProduct: `${prefixUrl}/product`,
    productType: `${prefixUrl}/product-type`,
    spaceChangeWaitlist: `${prefixUrl}/resident-company/spacechangewaitlist/param?`,
    getSpaceChangeWaitlist: `${prefixUrl}/resident-company/spacechangewaitlist/param?`,
    getPrivacyData: `${prefixUrl}/resident-company/privacy`,
    updatePrivacyData: `${prefixUrl}/resident-company/privacy`,
    updateSpaceChangeWaitlist: `${prefixUrl}/resident-company/spacechangewaitlist/priorityorder`,
    changeListItems: `${prefixUrl}/resident-company/spacechangewaitlist/items`,
    saveSpaceChangeWaitlistRequest: `${prefixUrl}/resident-company/spacechangewaitlist`,
    getCompanyDetailsByCompanyId: `${prefixUrl}/resident-company/forwaitlist`,
    updateWaitlistChangeRequest: `${prefixUrl}/resident-company/spacechangewaitlist`,
    updateWaitlistChangeRequestStatus: `${prefixUrl}/resident-company/spacechangewaitlist/status`,
    refreshToken: `${prefixUrl}/auth/refresh-token`,
    conferenceRoom: `${prefixUrl}/conference-room`,
    costConfig: `${prefixUrl}/cost-config`,
    equipment: `${prefixUrl}/equipment`,
    siteConfig: `${prefixUrl}/site-config`,
    eventsandtraining : `${prefixUrl}/events-trainings`,
    companyOnboard : `${prefixUrl}/onboarding`,
    partners : `${prefixUrl}/partners`,
    sponsors : `${prefixUrl}/sponsors`,
    companyOffboard : `${prefixUrl}/offboarding`,
    usa_location_map: `${serverUrl}${prefixUrl}/file/read-image?fileType=configuration&filename=location.png`,
    metrics: `${prefixUrl}/Metrics/biolabsMetrics`,
    businessMetrics: `${prefixUrl}/businessMetrics`,
    siteDemographics: `${prefixUrl}/Metrics/siteDemographics`,
    occupanybyRevenueAndPercentage: `${prefixUrl}/Metrics/occupanybyRevenueAndPercentage`,
    occupanybyRevenueAndPercentagebytype: `${prefixUrl}/Metrics/occupanybytypeAndrevenuebytype`,
    companySize: `${prefixUrl}/Metrics/company-Size`,
    companyTypes: `${prefixUrl}/Metrics/company-Types`,
    numberOfMemberandSumOfFundRaised: `${prefixUrl}/Metrics/numberOfMemberandSumOfFundRaised`,
    currentandgraduatecompanies: `${prefixUrl}/Metrics/currentandgraduatecompanies`,
    avgData: `${prefixUrl}/Metrics/avgData`,
    companyTab: prefixUrl + `/companyTab`,
    globalSponsor: `${prefixUrl}/globalsponsor`
};
